server:
  port: 8888
  servlet:
    context-path: /light
log:
  path: /data/testLog
  level: log
  fileName: testLog
auth:
  open: true
  tokenName: token
  passPaths: /sys/login  #多个以逗号分割 /sys/login, /user/get, ...
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: test
    password: test
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath*:com/light/business/*/mapper/*.xml